### ISSUE TITLE
Manually rescheduling a job

### ISSUE THREAD

**Issue by bjartek** [vgarvardt/gue#124] opened 2022-11-09 10:31 UTC
I am trying to mutate the job.RunAt field inside a job to have it try to run itself at a later time. I want to control when to do this myself in a job and not as s policy. 

Currently when I do this it works but i get the error 
`2022/11/09 11:26:42 Got an error on deleting a job level=error worker-pool-id=8d9cd5 worker-id=8d9cd5/worker-1 job-id=3 job-type=ChallengeFinisher error=conn busy`

I have a wrapper around a job where i check that if this jobs depdendentIds are not finished running it should wait for a given interval and try again. I would very much like to keep the id of this job as it is and not report this as an error.

**Comment by vgarvardt** [comment] 2022-11-09 18:22
Can you reproduce this issue with the test?

**Comment by bjartek** [comment] 2022-11-10 08:29
What is the expected behavior if I mutate a job while it is running and return nil? Should it delete the job or update it to schedule it at a later time?

**Comment by bjartek** [comment] 2022-11-10 08:40
I tried to create a standalone example here, but I cannot reproduce what I have in my private code even. Here if i mutate the job.RunAt field the job just finishes even though I told it to Run again later. 

In my private code if i mutate the RunAt field it will run later. Not sure what I am doing wrong here.

**Comment by bjartek** [comment] 2022-11-10 12:06
I think I have worked around this where I actually schedule a new entry every time i want to requeue something at a later interval, and that works fairly well. I could not reproduce the issue in another test so might just be something I did wrong in my private repo. Feel free to close this issue.

**Comment by vgarvardt** [comment] 2022-11-13 19:57
By design Job does not expect any changes outside of the library routines, so any modifications the the object may lead to an undefined behavior. Most likely in the next major version I'll change handler parameter from Job reference to the value to make it more explicit. But manual rescheduling can be a valid use case, will think on how to implement it in a nice way.

Will keep this issue open for now.

**Comment by vgarvardt** [comment] 2022-11-14 14:08
Yes, draft implementation works in more or less the same way - specific error types for manual rescheduling/discarding.

**Comment by vgarvardt** [comment] 2022-11-14 18:00
Will be something like https://github.com/vgarvardt/gue/pull/131

**Comment by bjartek** [comment] 2022-11-14 18:02
Nice!

**Comment by vgarvardt** [comment] 2022-11-14 22:37
Implemented in https://github.com/vgarvardt/gue/pull/131, will be released in `v5`.

**Closed by vgarvardt** 2022-11-14 22:37 UTC
